### basic settings

# site properties and page defaults
title: The O'Brien Lab
description: We seek to understand how evolution and ecology in host-microbiome interactions modify stress tolerance, and how stressors modify evolution and ecology of host-microbiome interactions
logo: images/duckweedlogo.png
header: images/Yellow Creek Duckweed.jpg
footer: images/Yellow Creek Duckweed.jpg
header-dark: false
footer-dark: false
baseurl: ""

# site social media and other links
links:
  email: anna.obrien@unh.edu
  google-scholar: QZG3zswAAAAJ&hl
  github: amob
  twitter: anna_mobrien
#  instagram: YourLabHandle
#  youtube: YourLabChannel

### advanced settings

# automatic citations
auto-cite:
#  plugins:
#    - name: sources
#      input:
#        - ../_data/sources.yaml
#  output: ../_data/citations.yaml
  plugins:
    - name: orcid
      input:
        - ../_data/orcid.yaml
  output: ../_data/citations.yaml



# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
