- id: doi:10.1101/2022.02.10.479958
  image: https://amob.github.io/images/HighPark Duckweed.jpg
  date: 2022-2-11
  tags:
    - preprint

- id: doi:10.1021/acs.est.1c03922
  date: 2022-3-19
  tags:
    - nanoplastics

- id: doi:10.7554/eLife.76105
  date: 2022-1-21
  tags:
    - adaptation
    - climate
    - opinion

- id: doi:10.1016/j.envres.2021.111727
  image: https://amob.github.io/images/Duckweed in plate.png
  date: 2022-1-1
  tags:
    - microplastics
    - plants and microbes


- id: doi:10.1002/ajb2.1743
  image: https://amob.github.io/images/Phenology Mt Rainier2014.png
  date: 2021-10-16
  tags:
    - plants and microbes
    - microbial influence on traits


- id: doi:10.1038/s41564-021-00957-1
  date: 2021-8-18
  tags:
    - opinion
   
- id: doi:10.1021/acsestwater.1c00090
  date: 2021-6-17
  tags:
    - nanoplastics
   
- id: doi:10.1002/etc.5140
  date: 2021-6-14
  tags:
    - microplastics

- id: doi:10.1098/rspb.2020.2483
  date: 2021-1-13
  tags:
    - host-microbiome

- id: doi:10.1101/2021.04.20.440703 
  date: 2021-4-2
  image: https://amob.github.io/images/MC teosinte.jpg
  tags:
    - plant-rhizosphere
   
- id: doi:10.1126/science.abb7222
  date: 2020-10-23
  tags:
    - plants and microbes
    - experimental evolution

- id: doi:10.1007/s00248-019-01452-1
  image: https://amob.github.io/images/Yellow Creek Duckweed.jpg
  date: 2020-3-2
  tags:
    - plants and microbes
    - stress

- id: doi:10.1002/ajb2.1404
  image: https://amob.github.io/images/Yellow Creek duckweed view2.jpg
  date: 2019-12-26
  tags:
    - plants and microbes
    - stress
    - salt

- id: doi:10.1021/acs.est.9b07040
  date: 2020-1-27
  tags:
    - nanoplastics

- id: doi:10.1111/mec.15059
  date: 2019-4-10
  tags:
    - opinion
    - plants and microbes

- id: doi:10.1111/evo.13818
  image: https://amob.github.io/images/covers/evo.v73.11.cover.gif
  date: 2019-8-7
  tags:
    - plant-rhizosphere
    - microbial influence on traits
  extra-links:
    - type: journal
      link: https://doi.org/10.1111/evo.13857


- id: doi:10.1086/700118
  date: 2018-10-31
  image: https://amob.github.io/images/MtRainier cushion plants.jpg
  tags:
    - mutualism
    - co-adaptation
    - stress


- id: doi:10.1371/journal.pone.0127630
  date: 2015-5-28
  tags:
    - plants and microbes

- id: doi:10.1600/036364414X680816
  date: 2014-6-1

- id: doi:10.1007/s11252-012-0250-7
  date: 2012-7-12
  image: https://amob.github.io/images/ForestShoresView.jpg
  tags:
    - urban
    - stress

#- id: doi:10.1016/j.csbj.2020.05.017
#  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
#  date: 2020-6-2
#  extra-links:
#    - type: manubot
#      link: https://greenelab.github.io/knowledge-graph-review/
#  tags:
#    - knowledge graphs
#
#- id: doi:10.1371/journal.pcbi.1007128
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  repo: greenelab/meta-review
#  extra-links:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#
#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
#  extra-links:
#    - type: preprint
#      link: https://doi.org/10.7287/peerj.preprints.3100v1
#    - type: manubot
#      link: https://greenelab.github.io/scihub-manuscript/
#    - type: source
#      link: https://github.com/greenelab/scihub-manuscript
#      text: Manuscript source
#    - type: source
#      link: https://github.com/greenelab/scihub
#      text: Analyses source
